spring.application.name=skill_drill
spring.main.allow-bean-definition-overriding=true

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/skill_drill
spring.datasource.username=postgres
spring.datasource.password=#Deep321

# Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Secret key
jwt.secret=TG9uZ1N0cmluZ1NhZmVBbmRTZWN1cmVTZWNyZXRLZXlGb3JEaWdpdGFsU2lnbg

# Send email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tiroledeep32@gmail.com
spring.mail.password=hxgghiksxuppfaat
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#logging.level.org.springframework.mail=DEBUG

#Files upload
# AI Configurations
spring.ai.chat.client.enabled=false

spring.ai.google.genai.api-key=${api_key}
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.chat.temperature=0.8

spring.ai.openai.api-key=${groq_key}
spring.ai.openai.chat.model=llama-3.3-70b-versatile
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.temperature=0.8
spring.ai.openai.chat.timeout=20s